name: Newman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar o Newman
        run: npm install -g newman

      - name: Executar coleção USERS
        run: |
          newman run Users.postman_collection.json \
            -e "Ambiente API.postman_environment.json"

      - name: Executar coleção AUTH
        run: |
          newman run Auth.postman_collection.json \
            -e "Ambiente API.postman_environment.json"